version: "3"

services:
  cluster-bsc-rpc: # This is the bootstrap node
    image: bsc-geth:docker-local
    env_file: .env
    ports:
      - 8545:8545
      - 8546:8546
    environment:
      NODE_ID: bsc-rpc
    volumes:
      - ./storage/bsc-rpc:/root/.ethereum
      - ./scripts:/scripts
      - ./config:/config
    command: ash /scripts/bsc-rpc.sh
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4gb
        reservations:
          cpus: '0.25'
          memory: 1gb

  cluster-bsc-validator1:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator1
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator1:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 3gb
        reservations:
          cpus: '0.25'
          memory: 1gb

  cluster-bsc-validator2:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator2
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator2:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 3gb
        reservations:
          cpus: '0.25'
          memory: 1gb

  cluster-bsc-validator3:
    image: bsc-geth:docker-local
    env_file: .env
    environment:
      NODE_ID: bsc-validator3
      BOOTSTRAP_HOST: cluster-bsc-rpc
    volumes:
      - ./storage/bsc-validator3:/root/.ethereum
      - ./scripts:/scripts
    command: ash /scripts/bsc-validator.sh
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: 3gb
        reservations:
          cpus: '0.25'
          memory: 1gb

  nginx:
    image: nginx:1.16-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  netstats:
    build: ./netstats
    ports:
      - 3000:3000
    environment:
      WS_SECRET: bscpwd
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500m
        reservations:
          cpus: '0.05'
          memory: 100m

  truffle-test:
    build: ./truffle-test
    command: /scripts/truffle-test.sh
    env_file: .env
    environment:
      RPC_HOST: cluster-bsc-rpc
      RPC_PORT: 8545
    volumes:
      - ./scripts:/scripts
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 500m
        reservations:
          cpus: '0.05'
          memory: 100m

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 99.99.0.0/16
